# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190408_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
