# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190526_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('change_customer_status', 'Can Change customer Status'),), 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
