# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideImage',
            new_name='SliderImage',
        ),
    ]
