# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import sliderimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0002_auto_20190228_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.FileField(upload_to=sliderimages.models.get_document_filename, verbose_name='SliderImage'),
        ),
    ]
