# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0003_auto_20190228_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
