# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0004_sliderimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
