# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0005_auto_20190405_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
