# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import sliderimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0006_sliderimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to=sliderimages.models.get_document_filename, verbose_name='SliderImage'),
        ),
    ]
