# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0007_auto_20190407_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='thumbnail',
            field=models.ImageField(default=1, editable=False, upload_to='sliderimage/'),
            preserve_default=False,
        ),
    ]
