# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import sliderimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('sliderimages', '0008_sliderimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to=sliderimages.models.get_thumbnail_filename),
        ),
    ]
