# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190403_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugs',
            new_name='slug',
        ),
    ]
