# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='new', max_length=16),
        ),
    ]
