# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190409_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='new', max_length=16),
        ),
    ]
