# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=252, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
