# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('pattern_name', 'pattern_code', 'product_name')]),
        ),
    ]
