# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20190301_1053'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='categories.Category'),
            preserve_default=False,
        ),
    ]
